files = [ 'stream/assets/*' ]

[gxt]

[meta]
'stream/carcols.meta' = 'CARCOLS_FILE'
'stream/carvariations.meta' = 'VEHICLE_VARIATION_FILE'
'stream/handling.meta' = 'HANDLING_FILE'
'stream/vehicles.meta' = 'VEHICLE_METADATA_FILE'